
name: Go Build
on:
  push:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags
  pull_request:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMMIT: ${{ github.sha }}

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          path: go/src/github.com/microservices-demo/user

      - name: lateststall buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build user and userdb Container
        run: make build-push

