
name: Go Build
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMMIT: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v2

       # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1     

      - name: Log in Docker Hub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build user and userdb Container
        run: make build-push

